[supervisord]
nodaemon=true
logfile=%(ENV_LOG_DIR)s/supervisord.log
pidfile=/var/run/supervisord.pid

[program:tigervnc]
environment=HOME="/home/%(ENV_USER)s",USER="%(ENV_USER)s",DISPLAY="%(ENV_DISPLAY)s"
command=/usr/bin/Xvnc %(ENV_DISPLAY)s
    -depth %(ENV_DISPLAY_DEPTH)s
    -geometry %(ENV_DISPLAY_WIDTH)sx%(ENV_DISPLAY_HEIGHT)s
    -localhost
    -rfbport %(ENV_VNC_PORT)s
    -AlwaysShared
    -SecurityTypes None
autorestart=true
priority=100
user=%(ENV_USER)s
stdout_logfile=%(ENV_LOG_DIR)s/tigervnc.log
stdout_logfile_maxbytes=10MB
redirect_stderr=true

[program:openbox]
environment=HOME="/home/%(ENV_USER)s",USER="%(ENV_USER)s",DISPLAY="%(ENV_DISPLAY)s"
command=openbox --config-file /etc/xdg/openbox/rc.xml
autorestart=true
priority=200
user=%(ENV_USER)s
stdout_logfile=%(ENV_LOG_DIR)s/openbox.log
stdout_logfile_maxbytes=10MB
redirect_stderr=true

[program:browser]
environment=HOME="/home/%(ENV_USER)s",USER="%(ENV_USER)s",DISPLAY="%(ENV_DISPLAY)s",GOOGLE_API_KEY=""
command=/opt/start-browser.sh
stopsignal=INT
autorestart=true
priority=300
user=%(ENV_USER)s
stdout_logfile=%(ENV_LOG_DIR)s/browser.log
stdout_logfile_maxbytes=10MB
redirect_stderr=true

[program:websocat]
environment=HOME="/home/%(ENV_USER)s",USER="%(ENV_USER)s"
command=/usr/local/bin/websocat
    -v --binary --exit-on-eof --ping-interval 30
    ws-l:0.0.0.0:%(ENV_WEBSOCKET_PORT)s
    tcp:localhost:%(ENV_VNC_PORT)s
autorestart=true
priority=400
user=%(ENV_USER)s
stdout_logfile=%(ENV_LOG_DIR)s/websocat.log
stdout_logfile_maxbytes=10MB
redirect_stderr=true

[program:nginx]
command=nginx -g "daemon off;"
autorestart=true
priority=500
user=root
stdout_logfile=%(ENV_LOG_DIR)s/nginx-access.log
stdout_logfile_maxbytes=10MB
stderr_logfile=%(ENV_LOG_DIR)s/nginx-error.log
stderr_logfile_maxbytes=10MB
